// 프로시저 CREATE
CREATE PROCEDURE CREATE_BOOK (
@NAME NVARCHAR(100),   
@PUBLISHER NVARCHAR(50),
@AUTHOR NVARCHAR(50),
@RETURN_CODE VARCHAR(1) OUTPUT   
)
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
	-- 트랜잭션 시작
		BEGIN TRAN
		INSERT INTO TBL_BOOK (NAME, PUBLISHHER, AUTHOR)
		VALUES (@NAME, @PUBLISHER, @AUTHOR)
		COMMIT TRAN
		SET @RETURN_CODE = 'S'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		SET @RETURN_CODE = 'E'
	END CATCH
	SET NOCOUNT OFF
END;

// ALTER문으로 프로시저 변경.  -> CREATE문에 덮어써도 됨
--ALTER PROC CREATE_BOOK(
--@NAME NVARCHAR(100),   
--@PUBLISHER NVARCHAR(50),
--@AUTHOR NVARCHAR(50),
--@RETURN_CODE VARCHAR(1) OUTPUT)
--AS
--BEGIN
--	INSERT INTO TBL_BOOK (NAME, PUBLISHHER, AUTHOR) VALUES (CONCAT(@NAME,'��'),@PUBLISHER,@AUTHOR)
--END

// 프로시저 조회
--sp_helptext 'CREATE_BOOK'

// 프로시저 실행. Format -> exec [프로시저 명] [파라미터]
--exec CREATE_BOOK '  ' , '  ' , '  ' , ' ';

// 테이블 조회
--SELECT * FROM TBL_BOOK;
