-- INSERT PROCEDURE MANUAL

-- Params 선언
CREATE PROCEDURE PROC_NAME_INSERT (
	@VAR1 INT
	, @VAR2 INT
)

AS
BEGIN

-- 상위 @BD_NUM의 개수의 Tuple 출력
SELECT TOP (@BD_NUM) *
FROM
	(
		SELECT IDX ...
		, CONVERT(VARCHAR(10), DATE, 120) AS DATE
		, ROW_NUMBER() OVER(ORDER BY IDX DESC) AS ROWNUM
		FROM BOARD_BBS		
	) T
  
WHERE T.ROWNUM >= ((@VAR1 - 1) * @VAR2 + 1 )
ORDER BY T.ROWNUM

END;
